name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo, pdo_mysql

      - name: Install Composer dependencies
        run: |
          composer install --no-dev --no-interaction --prefer-dist

      - name: Generate Laravel key
        run: |
          php artisan key:generate

      - name: Run PHP unit tests
        run: |
          php artisan test --env=production

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.7

      - name: Run Terraform output
        id: terraform_output
        run: |
          terraform output db_host > db_host.txt
          echo "DB_HOST=$(cat db_host.txt)" >> $GITHUB_ENV

      - name: Authenticate AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Docker image
        run: |
          docker build -t laravel-app:latest .

      - name: Authenticate Docker to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_URI }}

      - name: Push Docker image to AWS ECR
        run: |
          docker tag laravel-app:latest ${{ secrets.AWS_ECR_URI }}/laravel-app:latest
          docker push ${{ secrets.AWS_ECR_URI }}/laravel-app:latest

      - name: Deploy to EKS
        env:
          DB_HOST: ${{ env.DB_HOST }}
          DB_PORT: 3306
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}
          kubectl apply -f deployment.yaml
