name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to AWS ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.REGION }} \
        | docker login --username AWS \
        --password-stdin ${{ secrets.ECR_REPOSITORY }}

    - name: Build and Push Docker Image
      run: |
        docker build -t laravel-app .
        docker tag laravel-app:latest ${{ secrets.ECR_REPOSITORY }}:latest
        docker push ${{ secrets.ECR_REPOSITORY }}:latest

    - name: Deploy to Kubernetes
      run: |
        aws eks update-kubeconfig --region ${{ secrets.REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
